APP_ERROR_SEND_NOTIFICATION = True
APP_ERROR_RECIPIENT_EMAIL = None
APP_ERROR_SUBJECT_PREFIX = ""
APP_ERROR_MASK_WITH = "THIS_IS_MASK"
APP_ERROR_MASKED_KEY_HAS = ('key', 'password', 'secret')
APP_ERROR_URL_PREFIX = "/dev/error"
